base_dirs:
  # needed quick start
  testing_data: /Users/haonanchang/Projects/LGMCTS-D/output/struct_diffusion/struct_rearrange
  # testing_data: /Users/haonanchang/Projects/StructDiffusion/experiments/testing_data
  wandb_dir: /path/to/wandb_logs
  # needed for training diffusion
  data: /Users/haonanchang/Projects/LGMCTS-D/output/struct_diffusion/struct_rearrange
  # needed for training collision discriminator
  pairwise_collision_data: /path/to/pairwise_collision_data
  # needed for evaluation in physics sim
  # assets_dir: /path/to/acronym_handpicked_large
  # experiment: /path/to/experiments